name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'back/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/joaobdr-api-01/htdocs/api-01.joaobdr.com/Loja-2.1.0.0/back
            git pull origin main
            npm install
            pm2 restart 6